### PR TITLE
Remove libboost program options component dependency

### PR DESCRIPTION
**Pull request by finikorg**
This dependency is not used anyway so remove it.

### CODE REVIEW

**Review by ybernat — COMMENTED** [review]
So you want to remove the comment from https://github.com/01org/thunderbolt-software-user-space/pull/33/files#diff-c5853e13d92b2a2602fcaf17546b9f4aR252 and say that this will not happen?

**Comment by finikorg** [comment]
I was thinking to remove comment also but decided to leave it for now, do you think I shall remove it?

**Comment by ybernat** [comment]
If we plan to have it done, I don't see a reason to remove the dependency now. It maybe should be added in first place, but now that it's there, it makes sure everyone expects it to be used and keep the packages and installation process prepared for it. Does it make sense or I'm just mumbling?

**Comment by finikorg** [comment]
I think we do not need this extra dependency, the same with boost-filesystem, especially AFAIK most of functionality is already in standard C++ library.

**Comment by ybernat** [comment]
1. So you think the ToDo I referred to should be removed? Let's remove it then.
2. Filesystem isn't in C++ standard library, unless you are talking about C++17 (way too new for some distros).
3. ProgramOptions have no replacement in standard C++ (and nothing planned, as much as I aware of). So if we are interested in such a functionality in the future, Boost's one is the de facto standard to go with.

**Comment by finikorg** [comment]
@ybernat btw, I have removed TODOs.

**Comment by ybernat** [comment]
I suggest using https://github.com/catchorg/Clara
It's header-only, so it can be just added here (to `3rdparty/` dir), it's under BSD license so no problem with it, and it looks like it just fits to our needs.

**Pull request merged**
